title: 老李的博客
author: 老李
email: admin@wulawula.cn
description: 也许该写点什么了...
baseurl: ''
url: 'https://awulawula.github.io'
github_username: awulawula
theme: jekyll-theme-minimal
plugins:
  - jekyll-admin
