title: 老李的博客
email: admin@wulawula.cn
description: 也许该写点什么了...
baseurl: ''
url: 'https://awulawula.github.io'
twitter_username: awulawula
github_username: awulawula
theme: minima
plugins:
  - jekyll-admin
